version: "3"
services:
  db:
    image: 'postgres:latest'
    container_name: 'db'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: Comp