version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      - SERVER_PORT=${SERVER_PORT:-8080}
      - SERVER_CONTEXT_PATH=${SERVER_CONTEXT_PATH:-/api}
      - DB_URL=jdbc:postgresql://db:5432/Comp
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-changeme}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-604800000}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    depends_on:
      - db
    networks:
      - comp-network
    env_file:
      - .env

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=Comp
      - POSTGRES_USER=${DB_USERNAME:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - comp-network
    env_file:
      - .env

networks:
  comp-network:
    driver: bridge

volumes:
  postgres-data:
