import { createApi } from '@reduxjs/toolkit/query/react';

// Hardcoded list of countries to avoid external API call
const COUNTRIES = [
    { name: { common: 'Afghanistan' } },
    { name: { common: 'Albania' } },
    { name: { common: 'Algeria' } },
    { name: { common: 'Andorra' } },
    { name: { common: 'Angola' } },
    { name: { common: 'Antigua and Barbuda' } },
    { name: { common: 'Argentina' } },
    { name: { common: 'Armenia' } },
    { name: { common: 'Australia' } },
    { name: { common: 'Austria' } },
    { name: { common: 'Azerbaijan' } },
    { name: { common: 'Bahamas' } },
    { name: { common: 'Bahrain' } },
    { name: { common: 'Bangladesh' } },
    { name: { common: 'Barbados' } },
    { name: { common: 'Belarus' } },
    { name: { common: 'Belgium' } },
    { name: { common: 'Belize' } },
    { name: { common: 'Benin' } },
    { name: { common: 'Bhutan' } },
    { name: { common: 'Bolivia' } },
    { name: { common: 'Bosnia and Herzegovina' } },
    { name: { common: 'Botswana' } },
    { name: { common: 'Brazil' } },
    { name: { common: 'Brunei' } },
    { name: { common: 'Bulgaria' } },
    { name: { common: 'Burkina Faso' } },
    { name: { common: 'Burundi' } },
    { name: { common: 'Cabo Verde' } },
    { name: { common: 'Cambodia' } },
    { name: { common: 'Cameroon' } },
    { name: { common: 'Canada' } },
    { name: { common: 'Central African Republic' } },
    { name: { common: 'Chad' } },
    { name: { common: 'Chile' } },
    { name: { common: 'China' } },
    { name: { common: 'Colombia' } },
    { name: { common: 'Comoros' } },
    { name: { common: 'Congo' } },
    { name: { common: 'Costa Rica' } },
    { name: { common: 'Croatia' } },
    { name: { common: 'Cuba' } },
    { name: { common: 'Cyprus' } },
    { name: { common: 'Czech Republic' } },
    { name: { common: 'Denmark' } },
    { name: { common: 'Djibouti' } },
    { name: { common: 'Dominica' } },
    { name: { common: 'Dominican Republic' } },
    { name: { common: 'Ecuador' } },
    { name: { common: 'Egypt' } },
    { name: { common: 'El Salvador' } },
    { name: { common: 'Equatorial Guinea' } },
    { name: { common: 'Eritrea' } },
    { name: { common: 'Estonia' } },
    { name: { common: 'Eswatini' } },
    { name: { common: 'Ethiopia' } },
    { name: { common: 'Fiji' } },
    { name: { common: 'Finland' } },
    { name: { common: 'France' } },
    { name: { common: 'Gabon' } },
    { name: { common: 'Gambia' } },
    { name: { common: 'Georgia' } },
    { name: { common: 'Germany' } },
    { name: { common: 'Ghana' } },
    { name: { common: 'Greece' } },
    { name: { common: 'Grenada' } },
    { name: { common: 'Guatemala' } },
    { name: { common: 'Guinea' } },
    { name: { common: 'Guinea-Bissau' } },
    { name: { common: 'Guyana' } },
    { name: { common: 'Haiti' } },
    { name: { common: 'Honduras' } },
    { name: { common: 'Hungary' } },
    { name: { common: 'Iceland' } },
    { name: { common: 'India' } },
    { name: { common: 'Indonesia' } },
    { name: { common: 'Iran' } },
    { name: { common: 'Iraq' } },
    { name: { common: 'Ireland' } },
    { name: { common: 'Israel' } },
    { name: { common: 'Italy' } },
    { name: { common: 'Jamaica' } },
    { name: { common: 'Japan' } },
    { name: { common: 'Jordan' } },
    { name: { common: 'Kazakhstan' } },
    { name: { common: 'Kenya' } },
    { name: { common: 'Kiribati' } },
    { name: { common: 'Korea, North' } },
    { name: { common: 'Korea, South' } },
    { name: { common: 'Kosovo' } },
    { name: { common: 'Kuwait' } },
    { name: { common: 'Kyrgyzstan' } },
    { name: { common: 'Laos' } },
    { name: { common: 'Latvia' } },
    { name: { common: 'Lebanon' } },
    { name: { common: 'Lesotho' } },
    { name: { common: 'Liberia' } },
    { name: { common: 'Libya' } },
    { name: { common: 'Liechtenstein' } },
    { name: { common: 'Lithuania' } },
    { name: { common: 'Luxembourg' } },
    { name: { common: 'Madagascar' } },
    { name: { common: 'Malawi' } },
    { name: { common: 'Malaysia' } },
    { name: { common: 'Maldives' } },
    { name: { common: 'Mali' } },
    { name: { common: 'Malta' } },
    { name: { common: 'Marshall Islands' } },
    { name: { common: 'Mauritania' } },
    { name: { common: 'Mauritius' } },
    { name: { common: 'Mexico' } },
    { name: { common: 'Micronesia' } },
    { name: { common: 'Moldova' } },
    { name: { common: 'Monaco' } },
    { name: { common: 'Mongolia' } },
    { name: { common: 'Montenegro' } },
    { name: { common: 'Morocco' } },
    { name: { common: 'Mozambique' } },
    { name: { common: 'Myanmar' } },
    { name: { common: 'Namibia' } },
    { name: { common: 'Nauru' } },
    { name: { common: 'Nepal' } },
    { name: { common: 'Netherlands' } },
    { name: { common: 'New Zealand' } },
    { name: { common: 'Nicaragua' } },
    { name: { common: 'Niger' } },
    { name: { common: 'Nigeria' } },
    { name: { common: 'North Macedonia' } },
    { name: { common: 'Norway' } },
    { name: { common: 'Oman' } },
    { name: { common: 'Pakistan' } },
    { name: { common: 'Palau' } },
    { name: { common: 'Palestine' } },
    { name: { common: 'Panama' } },
    { name: { common: 'Papua New Guinea' } },
    { name: { common: 'Paraguay' } },
    { name: { common: 'Peru' } },
    { name: { common: 'Philippines' } },
    { name: { common: 'Poland' } },
    { name: { common: 'Portugal' } },
    { name: { common: 'Qatar' } },
    { name: { common: 'Romania' } },
    { name: { common: 'Russia' } },
    { name: { common: 'Rwanda' } },
    { name: { common: 'Saint Kitts and Nevis' } },
    { name: { common: 'Saint Lucia' } },
    { name: { common: 'Saint Vincent and the Grenadines' } },
    { name: { common: 'Samoa' } },
    { name: { common: 'San Marino' } },
    { name: { common: 'Sao Tome and Principe' } },
    { name: { common: 'Saudi Arabia' } },
    { name: { common: 'Senegal' } },
    { name: { common: 'Serbia' } },
    { name: { common: 'Seychelles' } },
    { name: { common: 'Sierra Leone' } },
    { name: { common: 'Singapore' } },
    { name: { common: 'Slovakia' } },
    { name: { common: 'Slovenia' } },
    { name: { common: 'Solomon Islands' } },
    { name: { common: 'Somalia' } },
    { name: { common: 'South Africa' } },
    { name: { common: 'South Sudan' } },
    { name: { common: 'Spain' } },
    { name: { common: 'Sri Lanka' } },
    { name: { common: 'Sudan' } },
    { name: { common: 'Suriname' } },
    { name: { common: 'Sweden' } },
    { name: { common: 'Switzerland' } },
    { name: { common: 'Syria' } },
    { name: { common: 'Taiwan' } },
    { name: { common: 'Tajikistan' } },
    { name: { common: 'Tanzania' } },
    { name: { common: 'Thailand' } },
    { name: { common: 'Timor-Leste' } },
    { name: { common: 'Togo' } },
    { name: { common: 'Tonga' } },
    { name: { common: 'Trinidad and Tobago' } },
    { name: { common: 'Tunisia' } },
    { name: { common: 'Turkey' } },
    { name: { common: 'Turkmenistan' } },
    { name: { common: 'Tuvalu' } },
    { name: { common: 'Uganda' } },
    { name: { common: 'Ukraine' } },
    { name: { common: 'United Arab Emirates' } },
    { name: { common: 'United Kingdom' } },
    { name: { common: 'United States' } },
    { name: { common: 'Uruguay' } },
    { name: { common: 'Uzbekistan' } },
    { name: { common: 'Vanuatu' } },
    { name: { common: 'Vatican City' } },
    { name: { common: 'Venezuela' } },
    { name: { common: 'Vietnam' } },
    { name: { common: 'Yemen' } },
    { name: { common: 'Zambia' } },
    { name: { common: 'Zimbabwe' } },
];

// Create a mock API slice for countries
export const countriesApiSlice = createApi({
    reducerPath: 'countriesApi',
    baseQuery: () => ({ data: null }), // Dummy base query
    endpoints: (builder) => ({
        getCountries: builder.query({
            queryFn: () => ({ data: COUNTRIES }), // Return hardcoded data
        }),
    }),
});

export const { useGetCountriesQuery } = countriesApiSlice;
